import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
  // metadataBase: new URL("https://amaanbhati.tech/"),
	// title: {
	// 	default: "Amaan Bhati",
	// 	template: "% | Amaan Bhati",
	// },
  title: "Amaan Bhati Resume",
	description:
		"Amaan Bhati is a result driven final year Computer Science student with a strong aptitude for development and proficiency in modern frameworks. Eager to contribute technical skills and innovation to a dynamic software engineering role in a cutting-edge tech environment. Recognized for being a quick learner with the ability to swiftly adapt to new technology stacks.",
	openGraph: {
		title: "Amaan Bhati",
		description:
			"Amaan Bhati is a result driven final year Computer Science student with a strong aptitude for development and proficiency in modern frameworks. Eager to contribute technical skills and innovation to a dynamic software engineering role in a cutting-edge tech environment. Recognized for being a quick learner with the ability to swiftly adapt to new technology stacks.",
		url: "https://amaanbhati.tech/",
		siteName: "Amaan Bhati",
		locale: "en_US",
		type: "website",
		images: [
			{
				url: "",
				width: 1200,
				height: 630,
				alt: "Amaan Bhati Web Developer",
			},
		],
	},
	robots: {
		index: true,
		follow: true,
		googleBot: {
			index: true,
			follow: true,
			"max-video-preview": -1,
			"max-image-preview": "large",
			"max-snippet": -1,
		},
	},
	twitter: {
		title: "Amaan Bhati",
		card: "summary_large_image",
		description:
			"Amaan Bhati is a result driven final year Computer Science student with a strong aptitude for development and proficiency in modern frameworks. Eager to contribute technical skills and innovation to a dynamic software engineering role in a cutting-edge tech environment. Recognized for being a quick learner with the ability to swiftly adapt to new technology stacks.",
		images: [""],
	},
	icons: {
		shortcut: "",
	},
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
